### PR TITLE
make the default tx a BCH tx

### PR DESCRIPTION
**Pull request by Danconnolly**
Updates Transaction class so that every new transaction is by default a BCH transaction.

### CODE REVIEW

**Comment by HashEngineering** [comment]
This is an important update.  It would eliminate these issues: #56, #4 for new users and developers.

What I am not sure about is if version 2 transactions alone trigger signing inputs properly for BCH.

Will this replace the SendRequest.setForkId requirement?

**Comment by Danconnolly** [comment]
You're right, version 2 is not quite the right thing. This needs more research, closing for now.

**Comment by HashEngineering** [comment]
We can make version > 2 transactions trigger SendRequest.setForkId(true).  Right now it is the other way around.

**Comment by HashEngineering** [comment]
Or perhaps we have SendRequest.setForkId(true) by default and then modify the tests that fail to use SendRequest.setForkId(false).

**Pull request closed without merging**
