### PR TITLE
Cash Address Enhancements

### PR DESCRIPTION
**Pull request by HashEngineering**
These changes were made to get this feature to work on Bitcoin Cash Wallet (android app).

Android uses a version of OpenJDK which does not have this class:  `javafx.util.Pair` so it was replaced with `org.apache.commons.lang3.tuple.ImmutablePair`;

`getFromFormattedAddress` was changed to allow for NetworkParameters to be null, in which case the the addr string must contain the prefix for the network.  This method will throw an exception if the provided params don't match the addr prefix.

BitcoinURI was updated to accept a Cash Address.

Tests were updated to test for the new functionality of getFromFormattedAddress.

### CODE REVIEW

**Comment by HashEngineering** [comment]
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.047 s <<< FAILURE! - in org.bitcoinj.core.CashAddressTest
[ERROR] org.bitcoinj.core.CashAddressTest  Time elapsed: 0.047 s  <<< ERROR!
java.io.FileNotFoundException: D:\...\bitcoinj\core\target\test-classes\org\bitcoinj\core\bch_addresses.csv (The system cannot find the path specified)
        at org.bitcoinj.core.CashAddressTest.loadAddressBatch(CashAddressTest.java:32)
```
Additionally, the loadAddressBatch method was changed due to the above error that I get on my system.  This error doesn't appear to happen with Travis.

Another method that is needed is CashAddress.fromString (which will take a string and create the correct Address object.

In bitcoinj 0.15, the developers have made Address an abstract class, while LegacyAddress and SegwitAddress (bech32 format) are derived from it.  This may be an interesting approach, however, if we choose to merge bitcoin 0.15 we will get some segwit commits.

**Comment by rafa-js** [comment]
This Address hierarchy makes a lot of sense, but I think we could implement it rather than get segwit commits. 
The more time passes, the more different the implementations will be. In fact, I get the impression we can remove some legacy pieces of code. They are useless for us.

**Comment by HashEngineering** [comment]
There are probably many legacy parts of the code, things that can be improved.  We can only do so much at a time, though.

Merging with 0.15 of bitcoinj (BTC) will be a different point of discussion.  We might want to cherry-pick commits rather than doing a merge command.

**Review by rafa-js — APPROVED** [review]
Tested on my app and seems to work fine

**Comment by HashEngineering** [comment]
Thanks for the feedback.

**Comment by HashEngineering** [comment]
We are still missing a function to take an string and convert it to the correct address object.  Currently this requires trying one format, catching the exception and trying the other format.

I haven't tested this with testnet addresses, but it is working well in my Bitcoin Cash Wallet app.

**Comment by rafa-js** [comment]
Yes, this function will be very common. I have my own implementation I can share with you later.

I'm testing with testnet addresses. It generates good addresses and sends transactions nice but if someone sends me using the cashaddr format the app doesn't notice about it. I can't check out the code now but I guess it's related with the way the library considers a transaction relevant checking if an address belongs to us or not. Can you confirm it doesn't happen on Mainnet?

**Comment by rseibane** [comment]
The implementation I use to create an `Address` from string:

```
import org.bitcoinj.core.Address;
import org.bitcoinj.core.AddressFormatException;
import org.bitcoinj.core.CashAddressFactory;
import org.bitcoinj.core.NetworkParameters;


public class AddressFactory {

    public static AddressFactory create() {
        return new AddressFactory();
    }

    public Address getAddress(NetworkParameters params, String plainAddress) {
        try {
            if ( plainAddress.length() == 58 ) {
                return CashAddressFactory.create().getFromBase58( params, plainAddress );
            } else {
                return CashAddressFactory.create().getFromFormattedAddress( params, plainAddress );
            }
        } catch ( AddressFormatException ex ) {
            return Address.fromBase58( params, plainAddress );
        }
    }
}

```

**Comment by rafa-js** [comment]
The implementation I use to create an `Address` from string: 
``` 
import org.bitcoinj.core.Address;
import org.bitcoinj.core.AddressFormatException;
import org.bitcoinj.core.CashAddressFactory;
import org.bitcoinj.core.NetworkParameters;

public class AddressFactory {
    
    public static AddressFactory create() {
        return new AddressFactory();
    }

    public Address getAddress(NetworkParameters params, String plainAddress) {
        try {
            if ( plainAddress.length() <= 34 ) {
                return CashAddressFactory.create().getFromBase58( params, plainAddress );
            } else {
                return CashAddressFactory.create().getFromFormattedAddress( params, plainAddress );
            }
        } catch ( AddressFormatException ex ) {
            return Address.fromBase58( params, plainAddress );
        }
    }
} 
```

**Comment by rafa-js** [comment]
Btw, `CashAddress` working on testnet 👍🏻

**Comment by HashEngineering** [comment]
@rseibane I am curious about your AddressFactory class.

If the string length is <=34, then it will create a CashAddress object using the legacy address.  Later if toString() is called, then it returns a cash address format string.  Does that cause any problems?

**Comment by rafa-js** [comment]
Any problem so far... Why you think it should cause any problem?

**Comment by HashEngineering** [comment]
It would depend on the use of the address.

A legacy address would be created as a CashAddress.  Later when toString is called, it would return a cash address.  This may be confusing to a user if they had entered a legacy address then later check their transaction info and it is displayed cash address format.

I will be looking at the scheme that bitcoinj 0.15 is using for handling their address types, though their scheme may not be complete either.  

I want to see the cash address format code consistently integrated into bitcoinj-cash.  Now it seems as separate optional module.  We will probably figure it out as we go.

**Comment by rafa-js** [comment]
Hmmm I see your point!
I don't think a user is thinking this way. If they are used to handle addresses I think they probably know about the CashAddress format.
Anyway in our app we don't show the address for the transaction details (only if an advanced user checks out the BlockExplorer). This is because we don't have to deal with this issue.

The CashAddress format or the base58 are kind of "dress up" a sequence of bytes. This bytes are the only important computationally. The rest are just different alternatives to represent it or build it. This is what makes me think this part should be sorted out as part of the user interaction, getting methods that give us flexibility to get the appropriate format depending of our needs. The rest of the scheme doesn't care about it.

**Comment by HashEngineering** [comment]
I see what you mean, but we can also consider users to include the developers who will be using this library.

I think that if an address object is created with a particular address type, then that address object's `toString` should return the same format.  I think this will help with debugging, logging and keeping all the unit tests passing.

Another thing that is needed is documentation for these new methods.

**Comment by rafa-js** [comment]
Something like this would solve the issue?

```
import org.bitcoinj.core.Address;
import org.bitcoinj.core.AddressFormatException;
import org.bitcoinj.core.CashAddressFactory;
import org.bitcoinj.core.NetworkParameters;

public class AddressFactory {
    
    public static AddressFactory create() {
        return new AddressFactory();
    }

    public Address getAddress(NetworkParameters params, String plainAddress) {
        if ( plainAddress.length() <= 34 ) {
            return Address.fromBase58( params, plainAddress );
        } else {
            return CashAddressFactory.create().getFromFormattedAddress( params, plainAddress );
        }
    }
} 
```

Additionally, since the `Address` includes a `toBase58()` method, how about include a `toCashAddressFormat()` instead of replace the `toString()` into the `CashAddress`? It would allow to get any address both in base58 and CashAddress format by explicit invocations. Also would increase the compatibility. 

What kind of documentation do you mean?

**Comment by HashEngineering** [comment]
@rseibane , yes that would probably solve the issue.

I think it would be useful to have these string functions for an address object:
`toBase58()` - explicit as you mention
`toCashAddressFormat()` - explicit as you mention
`toString()` - return the default format of the object

I haven't tried out AddressFactory in my app yet.  I will probably do that in the next month.

Documentation would be the JavaDoc comments that explain the new classes, methods, properties, parameters, etc.  @Danconnolly set up this site for our documentation:  http://www.javadoc.io/doc/cash.bitcoinj/bitcoinj-core

**Comment by rafa-js** [comment]
Included! https://github.com/rseibane/bitcoinj/commit/0cd2c71f958f4235d3c08dd49f58714d0c865b8a

**Comment by HashEngineering** [comment]
My last commit adds an implementation of AddressFactory based on @rseibane suggestion above.  My version will try to created the address object based on the cash address format then the legacy format.  If both fail, it will throw a new exception including the error messages from attempting to create the address from both formats.  

This still requires javadoc documentation.

I still want to look at bitcoinj 0.15 at its abstract Address class and the LegacyAddress and SegwitAddress class (in our case it is CashAddress).  I think if we used this scheme, the developers of bitcoinj-cash can use any format they want in their apps and all unit tests will pass while existing apps that use bitcoinj will need fewer changes to support the cash address format.  This could be done under a different pull request.  For now I will try to finish the documentation.

**Comment by HashEngineering** [comment]
I am reopening this because it is still a valid pull request to consider.

**Comment by Danconnolly** [comment]
This attempt to change the base branch to cash has made a mess. I've created a new PR #55 .

**Comment by rseibane** [comment]
I have found something about the BitcoinURI. It accepts either prefix `bitcoincash:` or `cashaddr:`. I consider should accept both for the same `NetworkParameters`. 

What do you think?

**Pull request closed without merging**
