### PR TITLE
Prevent hasTransactions returning null

### PR DESCRIPTION
**Pull request by brad1121**
non-critical but avoids an extra unnecessary null check/exception which annoyed me at one point.

### CODE REVIEW

**Comment by HashEngineering** [comment]
How does hasTransactions return `null`?

It would be helpful to see the call stack of such a case.

Android Studio does point out that List.isEmpty() can produce a NullPointerException.

the original method says:  `!this.transactions.isEmpty();` and it is possible that this `transactions = null` in the case that the block contains only the header.  Not sure if this is related to my question.

**Comment by brad1121** [comment]
Yea that would be it, block with only headers returns null. I think its cleaner it return false.

**Comment by HashEngineering** [comment]
https://github.com/bitcoinj/bitcoinj/commit/73fe9e6ab51501d498cf1a970aca208ea049adff

**Comment by Danconnolly** [comment]
Migrated to Bitcoin SV library.

**Pull request closed without merging**
